server:
  port: 8888


#easy-rpc:
#  application:
#    name: Test
#  center:
#    address: returnac.cn
#    port: 8848
#    group: TEST
##  protocol:
##    port: 22222
micro-rpc:
  application:
    name: Test
    version: 1.0.0
  registry:
    ip: 127.0.0.1
    port: 2181
  protocol:
    name: dubbo
    port: 20880
